### PR TITLE
Update troubleshooting.md

### PR DESCRIPTION
**Pull request by leesei**
wrt https://github.com/hexojs/hexo/issues/1735

### CODE REVIEW

**Comment by tommy351** [comment]
I think put the solution right in the documentation would be better than let users check the issue.

**Comment by leesei** [comment]
I hesitated because I cannot find documentation for `--max_old_space_size` in my manpage.
Using this PR as a placeholder for updates.

**Comment by tommy351** [comment]
You can find it in `node --v8-options`. It would be better to keep both solution and the link of issue in doc.

**Comment by leesei** [comment]
Great.

**Pull request closed without merging**
