### PR TITLE
add Starry

### PR DESCRIPTION
**Pull request by meethigher**
add Starry to Hexo

### CODE REVIEW

**Comment by meethigher** [comment]
## Check List

**Please read and check followings before submitting a PR.**

- [x] I want to publish my theme on Hexo official website.
  - [x] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
  - [x] `name` is unique.
  - [x] `link` URL is correct.
  - [x] `preview` URL is correct.
  - [x] `preview` URL web site is rendered correctly.
  - [x] Add a screenshot to `source/themes/screenshots`.
  - [x] Screenshot filename is same as value of `name`.
  - [x] Screenshot size is `800 * 500`.
  - [x] Screenshot file format is `png`.

- [ ] I want to publish my plugin on Hexo official website.
  - [ ] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
  - [ ] `name` is unique.
  - [ ] `link` URL is correct.

- [ ] Others (Update, fix, translation, etc...)

**Comment by meethigher** [comment]
> Please follow the theme publishing checklist, the one you just deleted when you submit the PR, before submitting your theme to Hexo.

I have already modified it, is it ok?

**Comment by SukkaW** [comment]
Please remove extra files and avoid extra changes.

**Comment by meethigher** [comment]
> Please remove extra files and avoid extra changes.

感谢大哥！！其实你给我发的英语我没咋看明白，哈哈~~~~

**Pull request merged**
