### PR TITLE
gulp.useRef.assets is no longer used

### PR DESCRIPTION
**Pull request by segayuu**
- [x] Read the [theme publishing doc](https://hexo.io/docs/themes#Publishing) or [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).

### CODE REVIEW

**Comment by tomap** [comment]
Are you sure? What was it used for before?

**Comment by segayuu** [comment]
see https://github.com/jonkemp/gulp-useref#migration-from-v2-api

**Comment by YoshinoriN** [comment]
@tomap 
Maybe according to [this migration](https://www.npmjs.com/package/gulp-useref#migration-from-v2-api).

@segayuu 
I think, code is seems no problem. But, IMHO you should request & approval our other maintainer review.

**Comment by segayuu** [comment]
@tomap @YoshinoriN I am sorry for the confusion. This PR is PR for #814. It will not be immediately merged into master.ter.

**Comment by tomap** [comment]
I'm too late, but LGTM

**Pull request merged**
