### PR TITLE
Replace dead preview - carbon

### PR DESCRIPTION
**Pull request by DiegoRBaquero**
SSL Error + Not really configured site

### CODE REVIEW

**Comment by NoahDragon** [comment]
You're right, the link is dead. However, in their repo, I saw another demo link: http://icylogic.github.io/carbon/

**Comment by DiegoRBaquero** [comment]
That's the link I'm replacing with

Diego R.

**Comment by DiegoRBaquero** [comment]
Feeling stupid, I actually meant to link the GitHub pages link. Fixed. Can be merged now (Squash it)

**Comment by NoahDragon** [comment]
Thanks. Merged.

**Pull request merged**
