### PR TITLE
theme: remove hexo-theme-spfk

### PR DESCRIPTION
**Pull request by curbengh**
## Check List

**Please read and check followings before submitting a PR.**

- [x] Others (Update, fix, translation, etc...)

The user violated GitHub ToS and the account has been blocked.

### CODE REVIEW

**Comment by luuman** [comment]
GitHub ToS?

Sage (GitHub Developer Support)Oct 7, 7:41 PM UTCHello,Thanks for contacting us. Your account was flagged for posting off-topic or unproductive comments in other users' repositories. We are a code hosting service and collaboration tool for software developers, and this activity violates our Terms of Service. We'll have to keep your account flagged for now.If you'd be willing to stop this kind of behavior and let us know how you intend to use GitHub going forward, we'd be happy to consider reinstating your account.Thanks,Sage
--

why?

**Comment by luuman** [comment]
I submitted it only three times and you reported it.

**Comment by YoshinoriN** [comment]
https://github.com/hexojs/site/pull/1155 is all.
We judged your PRs sounded malicious.

**Comment by luuman** [comment]
无语，我恶意提交？一共提交三次都是按照你们的要求去修改，却说我是恶意行为。把我账号封了。至于吗？好好的假期都不能

**Pull request merged**
