### PR TITLE
Update Vercel deployment guide

### PR DESCRIPTION
**Pull request by samsisle**
## Check List

**Please read and check followings before submitting a PR.**

Hello from the Vercel team!

Just submitting an update to the [Vercel section](https://hexo.io/docs/one-command-deployment#ZEIT-Now) in the one-command deployment doc. Unfortunately, I could only update the English version.

- [ ] I want to publish my theme on Hexo official website.
    - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [ ] `name` is unique.
    - [ ] `link` URL is correct.
    - [ ] `preview` URL is correct.
    - [ ] `preview` URL web site is rendered correctly.
    - [ ] Add a screenshot to `source/themes/screenshots`.
    - [ ] Screenshot filename is same as value of `name`.
    - [ ] Screenshot size is `800 * 500`.
    - [ ] Screenshot file format is `png`.
- [ ] I want to publish my plugin on Hexo official website.
    - [ ] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [ ] `name` is unique.
    - [ ] `link` URL is correct.
- [X] Others (Update, fix, translation, etc...)
    - Languages:
    - [X] `en` English
    - [X] `ko` Korean
    - [X] `pt-br` Brazilian Portuguese
    - [X] `ru` Russian
    - [X] `th` Thai
    - [X] `zh-cn` simplified Chinese
    - [X] `zh-tw` traditional Chinese

### CODE REVIEW

**Comment by SukkaW** [comment]
LGTM! But would you mind updating the guide for all languages? Simply copy the english will be fine, translation will be brought up later.

**Comment by samsisle** [comment]
I will copy-update the update to the other languages in English — is that ok? @SukkaW

**Comment by SukkaW** [comment]
> I will copy-update the update to the other languages in English — is that ok? @SukkaW

Yeah. That will be ok.

**Review by SukkaW — APPROVED** [review]

**Comment by SukkaW** [comment]
Merged, thanks!

**Pull request merged**
