### PR TITLE
Add Vanillia theme

### PR DESCRIPTION
**Pull request by snovey**
- [x] Read the [theme publishing doc](https://hexo.io/docs/themes#Publishing) or [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).

Add a theme named vanilla which is a plain theme.

### CODE REVIEW

**Comment by snovey** [comment]
Well……

The image link for the vanilla theme preview is invalid.

image

Who can help?

**Comment by YoshinoriN** [comment]
@snovey 
`themes.yml`'s `name` and filename must be the same.
Your file name is wrong. Would you please fix & create new PR?

**Comment by snovey** [comment]
I don't know how to continue to create a pull request on this page.

The new pull request has created. Please view it at the opened pull request list after my magic operates. 😂

**Comment by YoshinoriN** [comment]
> how to continue to create a pull request on this page.

It's impossible. New PR is okay. I merged the new PR #998.
Please check [themes](https://hexo.io/themes/)

Thanks :)

**Comment by snovey** [comment]
OK. It works. Thank you~

**Pull request merged**
