### PR TITLE
news: hexo-cli 3.0.0 & hexo-util 1.4.0 released

### PR DESCRIPTION
**Pull request by curbengh**
- [x] Others (Update, fix, translation, etc...)

### CODE REVIEW

**Comment by tomap** [comment]
wait until this is merged and adapt news :)
https://github.com/hexojs/hexo-cli/pull/122

**Comment by curbengh** [comment]
merged https://github.com/hexojs/hexo-cli/pull/122

**Comment by SukkaW** [comment]
IMHO, it is not needed to publish a new version of hexo-cli after https://github.com/hexojs/hexo-cli/pull/122 is merged. We can stick to hexo-cli@3.0.0 when we publish Hexo v4.

So the news is good to go then.

**Comment by curbengh** [comment]
Honestly I didn't actually get what @tomap meant. https://github.com/hexojs/hexo-cli/pull/122 is more of a package-lock update, `"hexo-util": "^1.0.0"` (before that PR) already covers hexo-util@1.4.0, so I agree with @SukkaW that hexo-cli@3.0.1 is not necessary.

**Pull request merged**
