### PR TITLE
docs: fix toc of github-pages & update menu i18n for zh-cn

### PR DESCRIPTION
**Pull request by SukkaW**
## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
    - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [ ] `link` URL is correct.
    - [ ] `preview` URL is correct.
    - [ ] `preview` URL web site is rendered correctly.
    - [ ] Add a screenshot to `source/themes/screenshots`.
    - [ ] Screenshot filename is same as value of `name`.
    - [ ] Screenshot size is `800 * 500`.
    - [ ] Screenshot file format is `png`.
- [ ] I want to publish my plugin on Hexo official website.
    - [ ] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [ ] `link` URL is correct.
- [x] Others (Update, fix, translation, etc...)

### CODE REVIEW

**Comment by curbengh** [comment]
The fix already in https://github.com/hexojs/site/pull/1125? you could also put the "one-command" translation in that PR.

**Comment by SukkaW** [comment]
Ops, I have messed up my local branches.

**Comment by curbengh** [comment]
I don't mind #1125 to include this, which is easier, instead of cleaning up two PRs.

**Comment by SukkaW** [comment]
I have cheery-picked https://github.com/hexojs/site/pull/1124/commits/9976e9bc0cb1880e20bca1b2eb4a70e540b32e06 into #1123

**Comment by SukkaW** [comment]
Superseded by #1123 & #1125

**Pull request closed without merging**
