### PR TITLE
chore(news): hexo-filter-responsive-images 1.4.0, 1.4.1 & hexo-asset-pipeline 1.7.0 release news

### PR DESCRIPTION
**Pull request by YoshinoriN**
* hexo-filter-responsive-images 1.4.0 & 1.4.1
* hexo-asset-pipeline 1.7.0

### CODE REVIEW

**Comment by YoshinoriN** [comment]
@tomap 
Thanks a replay. But, I'm sorry, I’m not sure what you mean :sob:
Should I dived this PR into two PR ?

**Comment by tomap** [comment]
I would do a single blog post instead of two

Le ven. 14 déc. 2018 à 11:33, YoshinoriN <notifications@github.com> a
écrit :

**Comment by YoshinoriN** [comment]
@tomap 
OK. I understand. I will re-create & push.

**Comment by YoshinoriN** [comment]
Done

**Comment by YoshinoriN** [comment]
@tomap 
Would you check it ?

**Comment by YoshinoriN** [comment]
Thanks @tomap 
I will merge this PR after fix the build failure.

**Pull request merged**
