### PR TITLE
add theme Chic

### PR DESCRIPTION
**Pull request by Sirice19**
- [x] Read the [theme publishing doc](https://hexo.io/docs/themes#Publishing) or [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).

### CODE REVIEW

**Comment by tomap** [comment]
Your repo contains a full hexo site, not just the theme folder:
https://hexo.io/docs/themes.html

**Comment by Sirice19** [comment]
My repo contains just theme folder in master branch,a full hexo site was deployed in gh-pages branch.

**Comment by Sirice19** [comment]
> Your repo contains a full hexo site, not just the theme folder:
> https://hexo.io/docs/themes.html



> Your repo contains a full hexo site, not just the theme folder:
> https://hexo.io/docs/themes.html

Excuse me, I think my repo url may be correct.
My repo contains just theme folder in master branch, a full hexo site was deployed in gh-pages branch which is used to preview. Could you check it again?I wish to get it merged soon.

**Comment by Sirice19** [comment]
> Your repo contains a full hexo site, not just the theme folder:
> https://hexo.io/docs/themes.html

Excuse me, I think my repo url may be correct.
My repo contains just theme folder in master branch, a full hexo site was deployed in gh-pages branch which is used to preview. Could you check it again?I wish to get it merged soon.

**Comment by YoshinoriN** [comment]
@tomap 
It seems this PR is no problem. IMO we can merge this. Would you please check again?

**Pull request closed without merging**
