### PR TITLE
news: hexo 5.0.0 & hexo-cli 4.1.0 released

### PR DESCRIPTION
**Pull request by SukkaW**
## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
    - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [ ] `name` is unique.
    - [ ] `link` URL is correct.
    - [ ] `preview` URL is correct.
    - [ ] `preview` URL web site is rendered correctly.
    - [ ] Add a screenshot to `source/themes/screenshots`.
    - [ ] Screenshot filename is same as value of `name`.
    - [ ] Screenshot size is `800 * 500`.
    - [ ] Screenshot file format is `png`.
- [ ] I want to publish my plugin on Hexo official website.
    - [ ] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [ ] `name` is unique.
    - [ ] `link` URL is correct.
- [x] Others (Update, fix, translation, etc...)
    - Languages:
    - [ ] `en` English
    - [ ] `ko` Korean
    - [ ] `pt-br` Brazilian Portuguese
    - [ ] `ru` Russian
    - [ ] `th` Thai
    - [ ] `zh-cn` simplified Chinese
    - [ ] `zh-tw` traditional Chinese

This should only be merged after hexo-cli@4.1.0 is released.

### CODE REVIEW

**Comment by curbengh** [comment]
the post is quite long, I think it's better to have hexo-cli in separate post.
https://github.com/hexojs/site/pull/1491

**Comment by curbengh** [comment]
I plan to release hexo-migrator-rss & hexo-migrator-wordpress in this weekend, perhaps this PR can include them.

**Comment by SukkaW** [comment]
> I plan to release hexo-migrator-rss & hexo-migrator-wordpress in this weekend, perhaps this PR can include them.

I'd rather give up this PR since it is mainly for Hexo 5.0.0. You can open a new PR to include hexo-cli.

**Comment by curbengh** [comment]
https://github.com/hexojs/site/pull/1497 https://github.com/hexojs/site/pull/1491

**Pull request closed without merging**
