### PR TITLE
List hexo-canonical-link plugin

### PR DESCRIPTION
**Pull request by tarunbatra**
Plugin to add canonical links for pages. By default, the url of the page will be set as canonical link. Other urls can be set by mentioning `canonical_url` in frontmatter of the page. Useful for SEO.

## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
    - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [ ] `link` URL is correct.
    - [ ] `preview` URL is correct.
    - [ ] `preview` URL web site is rendered correctly.
    - [ ] Add a screenshot to `source/themes/screenshots`.
    - [ ] Screenshot filename is same as value of `name`.
    - [ ] Screenshot size is `800 * 500`.
    - [ ] Screenshot file format is `png`.
- [x] I want to publish my plugin on Hexo official website.
    - [x] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [x] `link` URL is correct.
- [ ] Others (Update, fix, translation, etc...)

### CODE REVIEW

**Comment by SukkaW** [comment]
It seems that the plugin is duplicated with https://github.com/hexojs/hexo/pull/3701

**Comment by tarunbatra** [comment]
@SukkaW yeah seems like that PR covers the scope of this plugin and that of [hexo-auto-canonical](https://github.com/HyunSeob/hexo-auto-canonical).

**Comment by tarunbatra** [comment]
It is useful in cases where a blog post is a cross posted on multiple sites
(medium, dev.to, etc.) and also on your personal site. With this plugin you
can link to your medium blog and not confuse Google's algo.

**Comment by curbengh** [comment]
I see, I just read about [cross-domain](https://moz.com/blog/cross-domain-rel-canonical-seo-value-cross-posted-content) canonical tag. Can you mention that feature in the description? This is to let user know the difference.

also append your plugin to "plugins.yml", not prepend.

**Comment by tarunbatra** [comment]
@curbengh made the changes.

**Comment by curbengh** [comment]
Thanks, I further clarified the description.

Previously,
`Set canonical link for pages with support for external links and defaults to the page url.`

I don't think `defaults to...` is necessary for an intro. I added a comma in the middle to clarify that external link support applies to the _plugin_ not the _pages_.

**Pull request merged**
