### PR TITLE
add the plugin: hexo-stop-tag-plugins

### PR DESCRIPTION
**Pull request by think-in-universe**
- [x] Read the [theme publishing doc](https://hexo.io/docs/themes#Publishing) or [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).

### CODE REVIEW

**Comment by think-in-universe** [comment]
The PR https://github.com/hexojs/hexo/pull/3573 to hexojs/hexo should also be merged, to make sure this plugin works well when the markdown file contains code blocks.

**Comment by think-in-universe** [comment]
@tomap  hello, could you please help review the PR?

**Comment by think-in-universe** [comment]
@JLHwung and @tomap , could you please also help review this PR for the hexo plugins?

**Comment by JLHwung** [comment]
@think-in-universe Sorry for the late replay. Awesome job!

**Comment by think-in-universe** [comment]
@JLWwung, thanks for the review!

**Pull request merged**
