### PR TITLE
Add hexo-filter-image plugin

### PR DESCRIPTION
**Pull request by JoeyBling**
## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
    - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [ ] `link` URL is correct.
    - [ ] `preview` URL is correct.
    - [ ] `preview` URL web site is rendered correctly.
    - [ ] Add a screenshot to `source/themes/screenshots`.
    - [ ] Screenshot filename is same as value of `name`.
    - [ ] Screenshot size is `800 * 500`.
    - [ ] Screenshot file format is `png`.
- [x] I want to publish my plugin on Hexo official website.
    - [x] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [x] `link` URL is correct.
- [ ] Others (Update, fix, translation, etc...)

### CODE REVIEW

**Comment by JoeyBling** [comment]
I just want to submit the ```source/_data/plugins.yml``` file, But I don't know why pull request to bring all the documents again. How can I fix it

**Comment by JoeyBling** [comment]
Can anyone help me?

**Comment by curbengh** [comment]
The master branch of your fork has different commit history than the upstream (hexojs/site). You can try to rebase, but most probably there'll be merge conflict. The easiest way is to remove your fork and re-fork again. Then remove your git-cloned folder and clone your repo again.

In case you didn't backup, here's your commit:
```
- name: hexo-filter-image
  description: 自动为hexo中的图片映射绝对路径 | Automatically maps absolute paths to images in hexo
  link: https://github.com/JoeyBling/hexo-filter-image
  tags:
    - filter
    - image
    - path
    - asset
    - options
    - parameters
    - customization
```

---

I would advice not to touch the master branch (of your fork) except to sync with upstream. To sync,
``` sh
$ git remote add upstream https://github.com/hexojs/site
$ git checkout master
$ git fetch upstream
$ git rebase upstream/master
$ git push -u
```

Always push commit(s) (of your work) to a new branch. Once the pull request has been merged in the upstream, remove the branch in your local copy
```
$ git checkout master
$ git branch -D your-branch
```
and in your github repo.

**Comment by JoeyBling** [comment]
@curbengh Thank you very much!
Here's my new ` Pull requests`
> [Add hexo-filter-image plugin](https://github.com/hexojs/site/pull/1071)

**Pull request closed without merging**
