### PR TITLE
add plugins "hexo-seo-autopush" AND "hexo-minify"

### PR DESCRIPTION
**Pull request by lete114**
## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
  - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
  - [ ] `name` is unique.
  - [ ] `link` URL is correct.
  - [ ] `preview` URL is correct.
  - [ ] `preview` URL web site is rendered correctly.
  - [ ] Add a screenshot to `source/themes/screenshots`.
  - [ ] Screenshot filename is same as value of `name`.
  - [ ] Screenshot size is `800 * 500`.
  - [ ] Screenshot file format is `png`.
- [x] I want to publish my plugin on Hexo official website.
  - [x] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
  - [x] `name` is unique.
  - [x] `link` URL is correct.
- [ ] Others (Update, fix, translation, etc...)
  - Languages:
  - [ ] `en` English
  - [ ] `ko` Korean
  - [ ] `pt-br` Brazilian Portuguese
  - [ ] `ru` Russian
  - [ ] `th` Thai
  - [ ] `zh-cn` simplified Chinese
  - [ ] `zh-tw` traditional Chinese

### CODE REVIEW

**Review by jiangtj — APPROVED** [review]
👍

**Review by SukkaW — APPROVED** [review]

**Comment by tomap** [comment]
Seems ok
 Please fix conflict so we can merge :)

**Comment by lete114** [comment]
> Seems ok
> Please fix conflict so we can merge :)

What? I don't quite understand. What's going on

**Comment by lete114** [comment]
What seems to be the problem?

**Comment by SukkaW** [comment]
> What seems to be the problem?

Never mind. I can fix the conflict at my side.

**Comment by lete114** [comment]
> Never mind. I can fix the conflict at my side.

OK  thank you.

**Comment by SukkaW** [comment]
Added in https://github.com/hexojs/site/commit/dd87e650ec559efcc5934e89c3363a06b90bdb43

**Pull request closed without merging**
