### PR TITLE
docs: v7.0.0 changes

### PR DESCRIPTION
**Pull request by D-Sketon**
## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
  - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
  - [ ] `name` is unique.
  - [ ] `link` URL is correct.
  - [ ] `preview` URL is correct.
  - [ ] `preview` URL web site is rendered correctly.
  - [ ] Add a screenshot to `source/themes/screenshots`.
  - [ ] Screenshot filename is same as value of `name`.
  - [ ] Screenshot size is `800 * 500`.
  - [ ] Screenshot file format is `png`.
- [ ] I want to publish my plugin on Hexo official website.
  - [ ] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
  - [ ] `name` is unique.
  - [ ] `link` URL is correct.
- [x] Others (Update, fix, translation, etc...)
  - Languages:
  - [x] `en` English
  - [ ] `ru` Russian
  - [x] `zh-cn` simplified Chinese
  - [x] `zh-tw` traditional Chinese

> **Note**
>
> No need to translate `ko`, `pt-br`, `th` languages if you submit a PR for documentation.

> **Warning**
>
> `ko`, `pt-br`, `th` languages document are inactive. Please, submit issue if you want to continuous contribution to them.

### CODE REVIEW

**Comment by D-Sketon** [comment]
I'm not sure the required Node.js version. Can anyone help?

**Comment by yoshinorin** [comment]
@D-Sketon 
> I'm not sure the required Node.js version. Can anyone help?


Perhaps...

Hexo version | Minimum (Node.js version) | Less than (Node.js version)
-- | -- | --
7.0+ | 14.0.0 | latest
6.2+ | 12.13.0 | latest

**Comment by yoshinorin** [comment]
Updated https://github.com/hexojs/hexo/releases/tag/v7.0.0

**Comment by D-Sketon** [comment]
close #2103

**Review by yoshinorin — APPROVED** [review]
👍

**Pull request merged**
