### PR TITLE
Added new theme - Yin

### PR DESCRIPTION
**Pull request by Yin-Hongwei**

### CODE REVIEW

**Comment by Yin-Hongwei** [comment]
ok

**Comment by Yin-Hongwei** [comment]
> Please upload screenshot and finish the checklist before you submit you new theme.
> 
> When you open this PR, where will be a checklist in `<textarea>`, and you just deleted it. Find it back and fill it.

OK

**Comment by curbengh** [comment]
@Yin-Hongwei 
This is the checklist:
```
## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
    - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [ ] `link` URL is correct.
    - [ ] `preview` URL is correct.
    - [ ] `preview` URL web site is rendered correctly.
    - [ ] Add a screenshot to `source/themes/screenshots`.
    - [ ] Screenshot filename is same as value of `name`.
    - [ ] Screenshot size is `800 * 500`.
    - [ ] Screenshot file format is `png`.
```

**Comment by curbengh** [comment]
There is a merge conflict due to outdated branch. Here's how to resolve:
``` sh
$ git clone https://github.com/Yin-Hongwei/site hexo-site
$ cd hexo-site
$ git ch master
$ git remote add upstream https://github.com/hexojs/site
$ git checkout master
$ git fetch upstream
$ git rebase upstream/master
$ git push -u
```

Now you have sync your fork's master, next is re-commit to your branch
``` sh
$ git branch -D patch-1
$ git checkout -b patch-1
```

Add the following lines to "source/_data/themes.yml" again:
```
- name: Yin
  description: A Simple Theme for hexo.
  link: https://github.com/Yin-Hongwei/hexo-theme-Yin
  preview: https://yin-hongwei.github.io/
  tags:
    - Beautiful
    - cool
    - hexo-theme
    - Simple
```

and 800x500 screenshot to  "source/themes/screenshots/Yin.jpg". Commit the change,
``` sh
$ git add .
$ git commit -a -m "Add hexo-theme-Yin"
$ git push origin patch-1 -f
```

**Comment by stevenjoezhang** [comment]
Closing due to source repo deletion and merge conflict. Please open a new Pull Request if necessary.

**Pull request closed without merging**
