### PR TITLE
docs: fix hyperlink 404 error

### PR DESCRIPTION
**Pull request by D-Sketon**
## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
  - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
  - [ ] `name` is unique.
  - [ ] `link` URL is correct.
  - [ ] `preview` URL is correct.
  - [ ] `preview` URL web site is rendered correctly.
  - [ ] Add a screenshot to `source/themes/screenshots`.
  - [ ] Screenshot filename is same as value of `name`.
  - [ ] Screenshot size is `800 * 500`.
  - [ ] Screenshot file format is `png`.
- [ ] I want to publish my plugin on Hexo official website.
  - [ ] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
  - [ ] `name` is unique.
  - [ ] `link` URL is correct.
- [x] Others (Update, fix, translation, etc...)
  - Languages:
  - [x] `en` English
  - [x] `ru` Russian
  - [ ] `zh-cn` simplified Chinese
  - [x] `zh-tw` traditional Chinese

`zh-cn` see #1943

> **Note**
>
> No need to translate `ko`, `pt-br`, `th` languages if you submit a PR for documentation.

> **Warning**
>
> `ko`, `pt-br`, `th` languages document are inactive. Please, submit issue if you want to continuous contribution to them.

### CODE REVIEW

**Review by stevenjoezhang — APPROVED** [review]

**Comment by D-Sketon** [comment]
some urls like http://paularmstrong.github.io/swig/ and https://github.com/hexojs/hexo-util/blob/master/lib/prism.js have 404 error and can't be fixed

**Comment by stevenjoezhang** [comment]
@D-Sketon You can update them like this:
- https://node-swig.github.io/swig-templates/
- https://github.com/hexojs/hexo-util/blob/master/lib/prism.ts 
- https://github.com/hexojs/hexo-util/blob/master/lib/highlight.ts 
- https://github.com/minimistjs/minimist

**Comment by stevenjoezhang** [comment]
There are also duplicate links in `/source/zh-cn/docs/troubleshooting.md` need to be removed

**Comment by D-Sketon** [comment]
do `ko`, `pt-br` and `th` languages need to be changed?

**Comment by D-Sketon** [comment]
http://pow.cx in https://hexo.io/docs/server seems to be pointing to the wrong site

**Comment by stevenjoezhang** [comment]
Pow is no longer maintained: https://github.com/basecamp/pow
You can open another pull request to remove relevant docs

**Pull request merged**
