### PR TITLE
docs(configuration): add ignore

### LINKED ISSUE #1095: Add docs about ignore configuration usage
This feature is added in https://github.com/hexojs/hexo/pull/2631

### PR DESCRIPTION
**Pull request by curbengh**
- [x] Others (Update, fix, translation, etc...)

Closes #1095 

Related: https://github.com/hexojs/hexo/pull/3797

### CODE REVIEW

**Comment by SukkaW** [comment]
For most users, it is something quite confuse.

For me, I assume `include` and `exclude` is used to control what to be included or excluded statically, `.nojekyll` (as excluded by Hexo's default) as an example. While `ignore` will exclude files during render process so neither will they be transformed nor be included in the `public` dir.

**Comment by curbengh** [comment]
I also find it confusing myself. I see `ignore:` as a stop-gap workaround for https://github.com/hexojs/hexo/issues/2179 

Perhaps, we could drop `ignore:` and enhance `include`/`exclude` to include every folder (instead of just `source/`), v5 roadmap perhaps?

**Comment by SukkaW** [comment]
@curbengh 

Maybe not.

`include` / `exclude` determines whether files should be copied into `public` dir. For example, `.nojekyll` should be included. And `.nojekyll` will neither be rendered nor transformed.

There is also an option, `skip_render`, which is used do determines a "renderable" files (Maybe an HTML or a JSON file) should be rendered or not.

**Comment by curbengh** [comment]
> `include` / `exclude` determines whether files should be copied into public dir.

`ignore:` also does that, in addition to ignoring files from `watch`.

If `include`/`exclude` can be enhanced to cover every folder, for example `include` can be used to include `_foo.js` in `themes/`.

**Comment by SukkaW** [comment]
@curbengh a enhanced version of `include` / `exclude` requires update current config to `source/` prefixed. It is a breaking changes and I agree to add it to Hexo v5 roadmap.

**Comment by curbengh** [comment]
cc @seaoak, thought you might be interested to our discussion.

**Comment by seaoak** [comment]
I think this PR will close hexojs/hexo#2855.

For `skip_render:` option, the explanation in [the comment](https://github.com/hexojs/hexo/issues/2855#issuecomment-345786880) in hexojs/hexo#2855 seems very clear.

For `include:` and `exclude:` option, I think @SukkaW 's comment above is very clear.
> `include` / `exclude` determines whether files should be copied into `public` dir.

Might I also add, `exclude:` takes priority over `include:`.
https://github.com/hexojs/hexo/blob/master/lib/plugins/processor/asset.js#L111-L113
But because depending on this behavior might not be recommended,
no additional explanation will be necessary.

For `ignore:` option, it is difficult to explain because only this option is for different layer.
I think I will not recommend this option to users who don't know enough about Hexo's implementation.
I think this option should be used as a work-around to avoid performance or system-resource issue.
But I don't have good idea for documentation of this option...(sorry

**Comment by SukkaW** [comment]
@seaoak 
FYI, https://github.com/hexojs/hexo/commit/4eaec8ac2219eacddb1222a1374543738e983c8f has ignored `node_modules` inside `themes` dir. But when I run `hexo clean && hexo g --debug`, I can still see `node_modules` under `themes` dir have been processed.

The problems might be here: https://github.com/hexojs/hexo/blob/c1bbac3bfa633d7a283bc0885e6c0775769c6801/lib/theme/processors/source.js#L30

**Comment by curbengh** [comment]
> @seaoak
> FYI, [hexojs/hexo@4eaec8a](https://github.com/hexojs/hexo/commit/4eaec8ac2219eacddb1222a1374543738e983c8f) has ignored `node_modules` inside `themes` dir. But when I run `hexo clean && hexo g --debug`, I can still see `node_modules` under `themes` dir have been processed.

My understanding is that https://github.com/hexojs/hexo/pull/3797 + `ignore: **/themes/*/node_modules` config (currently not default yet) should prevent the folder from being processed and shouldn't show up in debug mode. I'll test it.

Anyway, we're digressing from this PR. I assume everyone here agree `ignore:` option should be documented, yes? If the commit looks fine, I'll duplicate to other languages.

**Comment by SukkaW** [comment]
`ignore:` options works fined. Only https://github.com/hexojs/hexo/commit/4eaec8ac2219eacddb1222a1374543738e983c8f is not works as it should be.

And I think it is ok to duplicate to other languages.

**Comment by curbengh** [comment]
Added to other langs.

**Pull request merged**
