### PR TITLE
Update theme amber preview image

### PR DESCRIPTION
**Pull request by Mitscherlich**
RT

### CODE REVIEW

**Comment by Mitscherlich** [comment]
Sorry. The previous image is transparent. That looks horrible.
I know that blames on me and I checked this time. Thx! 🙏🙏🙏

**Comment by tomap** [comment]
Hi, could you do two things:
1/ shrink your image to 800*500 see https://hexo.io/docs/themes#Publishing
2/ process it with a shrinker like https://tinypng.com/ => 50% weight gain

Thank you

**Comment by Mitscherlich** [comment]
Ok. Both done. But the ci failed due to nunjucks cannot be installed. Switch ci node.js version to `lts/*` may solve this problem. 💚 

https://github.com/hexojs/site/blob/eaedeef5a915490647ce1b7cba9d0bf052615613/.travis.yml#L5-L6

**Comment by YoshinoriN** [comment]
Thank you for your advice :blush:
We will fix travisCI settings.

**Pull request merged**
