### PR TITLE
add hexo-deployer-ftpupload plugin

### PR DESCRIPTION
**Pull request by abcdGJJ**
add hexo-deployer-ftpupload plugin

### CODE REVIEW

**Comment by abcdGJJ** [comment]
oh, CI has some errors, what can I do?

**Comment by YoshinoriN** [comment]
@abcdGJJ 
No problem. You don't have anything :blush:
I will check travisCI settings later.

Btw, what is the difference [hexo-deployer-ftpupload](https://github.com/abcdGJJ/hexo-deployer-ftpupload) ? I think use friendly, if documents (e.g. README) exists about explanation it. :wink:

Thank you!

**Comment by abcdGJJ** [comment]
oh, I have never known hexo-deployer-ftpsync until you said. I will try that.

**Comment by YoshinoriN** [comment]
No problem. Thank you create Pull-Request.

**Pull request closed without merging**
