### PR TITLE
Add Inferno.js JSX renderer

### PR DESCRIPTION
**Pull request by ppoffice**
## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
    - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [ ] `name` is unique.
    - [ ] `link` URL is correct.
    - [ ] `preview` URL is correct.
    - [ ] `preview` URL web site is rendered correctly.
    - [ ] Add a screenshot to `source/themes/screenshots`.
    - [ ] Screenshot filename is same as value of `name`.
    - [ ] Screenshot size is `800 * 500`.
    - [ ] Screenshot file format is `png`.
- [x] I want to publish my plugin on Hexo official website.
    - [x] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [x] `name` is unique.
    - [x] `link` URL is correct.
- [ ] Others (Update, fix, translation, etc...)
    - Languages:
    - [ ] `en` English
    - [ ] `ko` Korean
    - [ ] `pt-br` Brazilian Portuguese
    - [ ] `ru` Russian
    - [ ] `th` Thai
    - [ ] `zh-cn` simplified Chinese
    - [ ] `zh-tw` traditional Chinese

### CODE REVIEW

**Comment by ppoffice** [comment]
BTW, do you accept incoming repo transfer?

**Comment by SukkaW** [comment]
> BTW, do you accept incoming repo transfer?

Yes, we do accept!

**Review by SukkaW — APPROVED** [review]

**Comment by ppoffice** [comment]
@SukkaW Seems like I have to be a member of hexojs to transfer to repo to you. Or I can add one of the hexojs members as repo admin so that he/she can do the transfer instead. Please advise on how to precede.

**Comment by SukkaW** [comment]
@ppoffice As far as I remember, we did send you a invitation to join @hexojs/core team before.

@YoshinoriN @NoahDragon @segayuu Would you mind resending the invitation? `plugin` team should be fine.

**Comment by YoshinoriN** [comment]
@ppoffice @SukkaW 
I sent an invitation (plugin team) to @ppoffice :)

**Comment by ppoffice** [comment]
@YoshinoriN Thank you. I will be activity maintaining the plugin I'm about to transfer. However, I cannot make the same guarantee for other Hexo repos. Also, do you have any other communication channels for Hexo maintainers apart from GitHub?

**Comment by SukkaW** [comment]
> Do I need to transfer the NPM package to you as well?

Simply add a few people as owner will be fine. `yoshinorin` as @YoshinoriN, `curben` as @curbengh 

> Do you have any other communication channels for Hexo maintainers apart from GitHub?

Currently, no.

**Pull request merged**
