### PR TITLE
Update themes.yml

### PR DESCRIPTION
**Pull request by cofess**
Add a new theme,thanks!

### CODE REVIEW

**Comment by NoahDragon** [comment]
Please also add pic for the theme.

**Comment by cofess** [comment]
OK,I have already add pic for the theme.

**Comment by NoahDragon** [comment]
I couldn't see it in this PR. Have you added it to the https://github.com/hexojs/site/tree/master/source/themes/screenshots folder? The name should be same as the theme name.

**Comment by cofess** [comment]
I'm so sorry,I have add the pic to the wrong place.I have already add a new PR.Please check it,thanks!

**Comment by NoahDragon** [comment]
Great, it merged. Thanks for the contribution.
https://github.com/hexojs/site/pull/533

**Pull request closed without merging**
