### PR TITLE
fun themes

### PR DESCRIPTION
**Pull request by homeant**
fun

### CODE REVIEW

**Comment by SukkaW** [comment]
Please, fill in the checklist you just deleted.

**Comment by SukkaW** [comment]
Also, please reupload your thumbnail pictures. There must be something wrong with that png file.

**Comment by homeant** [comment]
- [*] I want to publish my theme on Hexo official website.
    - [*] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [*] `link` URL is correct.
    - [*] `preview` URL is correct.
    - [*] `preview` URL web site is rendered correctly.
    - [*] Add a screenshot to `source/themes/screenshots`.
    - [*] Screenshot filename is same as value of `name`.
    - [*] Screenshot size is `800 * 500`.
    - [*] Screenshot file format is `png`.
- [*] I want to publish my plugin on Hexo official website.
    - [*] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [*] `link` URL is correct.
- [*] Others (Update, fix, translation, etc...)

**Comment by homeant** [comment]
- [x] I want to publish my theme on Hexo official website.
    - [x] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [x] `link` URL is correct.
    - [x] `preview` URL is correct.
    - [x] `preview` URL web site is rendered correctly.
    - [x] Add a screenshot to `source/themes/screenshots`.
    - [x] Screenshot filename is same as value of `name`.
    - [x] Screenshot size is `800 * 500`.
    - [x] Screenshot file format is `png`.
- [x] I want to publish my plugin on Hexo official website.
    - [x] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [x] `link` URL is correct.
- [x] Others (Update, fix, translation, etc...)

**Pull request merged**
