### PR TITLE
add Hexo draft Initialize option

### PR DESCRIPTION
**Pull request by tmirun**

### CODE REVIEW

**Comment by tcrowe** [comment]
Some background on this would be helpful. Why both `draft` and `drafts`?

**Comment by tmirun** [comment]
hey guy, i see in the source code accept the both option, so i write draft and drafts

**Comment by tcrowe** [comment]
That's a good reason :smiley_cat:

**Comment by tcrowe** [comment]
Thank you for your patience and the contribution tmirun

**Pull request merged**
