### PR TITLE
Add theme Yilia-plus

### PR DESCRIPTION
**Pull request by JoeyBling**
Hello, I Add theme **yilia-plus**
> Dedicate a theme, continue to support！
Thanks!

### CODE REVIEW

**Comment by JoeyBling** [comment]
Can someone take care of that

**Comment by tomap** [comment]
I made a comment. Could you remove the two tags with the theme name? 
You can even do it on GitHub via an edit button

**Comment by JoeyBling** [comment]
> 我发表了评论。你能用主题名称删除这两个标签吗？
> 您甚至可以通过编辑按钮在GitHub上执行此操作

Sure, I've deleted the theme tags

**Comment by JoeyBling** [comment]
> I made a comment. Could you remove the two tags with the theme name?
> You can even do it on GitHub via an edit button

Sure, I've deleted the theme tags

**Pull request merged**
