### PR TITLE
add new theme Concise

### PR DESCRIPTION
**Pull request by Sanonz**
A simple theme based on hexo-theme-landscape.

### CODE REVIEW

**Comment by JLHwung** [comment]
Could you rebased on the master?

**Comment by Sanonz** [comment]
@JLHwung 没有rebase，我fork过来直接改完pr的😂

**Comment by JLHwung** [comment]
@Sanonz Next time please rebase on the master for a cleaner history. Thank you.

**Comment by Sanonz** [comment]
@JLHwung 好的，麻烦了哈

**Pull request merged**
