### PR TITLE
Shrink some images, and convert some jpg to png

### PR DESCRIPTION
**Pull request by tomap**

### CODE REVIEW

**Comment by tomap** [comment]
the build issue come from https://github.com/mozilla/nunjucks/pull/1161
we will need to wait for the fix

**Comment by tomap** [comment]
It seems yarn install --ignore-engines would solve our issue, or use the lts version of node, as suggested on another pr

**Comment by YoshinoriN** [comment]
@tomap 
I think that [lts setting](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions) at travisCI is better than `yarn install --ignore-engines`.
I suppose, npm package's owner set `engines` with the intent.

**Comment by JLHwung** [comment]
I suggest add [imagemin-lint-staged](https://github.com/tomchentw/imagemin-lint-staged) in the lint-staged + husky manner:
```
{
+ "husky": {
+   "hooks": {  
+     "pre-commit": "lint-staged"
+   }
+ },
+ "lint-staged": {
+   "*.{png,jpeg,jpg,gif,svg}": ["imagemin-lint-staged", "git add"]
+ }
}
```

so that
- all image will be optimized once they are included in git commit (typically for theme author adding new snapshots)
- the image will be only optimized once as they are unchanged
- we don't reply on maintainer to minify them as a task.

**Comment by weyusi** [comment]
@tomap @YoshinoriN I suggest to move travis discussion to a separate issue https://github.com/hexojs/site/issues/798.

**Comment by NoahDragon** [comment]
As the travis-ci is fixed, can wait to see this change merged. :wink:

**Comment by tomap** [comment]
Build fixed

**Pull request merged**
