### PR TITLE
Update themes.yml

### PR DESCRIPTION
**Pull request by code004Accepted**
- [x] Read the [theme publishing doc](https://hexo.io/docs/themes#Publishing) or [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).

### CODE REVIEW

**Comment by code004Accepted** [comment]
> Would you please add a screenshot?
> And your [preview site](https://code004.ml/hexo-theme-materialized/) seems broken.
> 
> Thanks :)

Screenshots: (words in Chinese)









The preview site is unavalible right now. It will be avalible as soon as possible. Thanks

**Comment by code004Accepted** [comment]
> Would you please add a screenshot?
> And your [preview site](https://code004.ml/hexo-theme-materialized/) seems broken.
> 
> Thanks :)

@YoshinoriN I updated the file. The preview site is ready and the link of the repo has changed.

So... Should I add the link of the screenshot to the file or should I just provide the link of the screenshot? Thanks.

**Comment by code004Accepted** [comment]
The screenshot is here:
https://camo.githubusercontent.com/01969bc337d747811d127a404416b982049031f5/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30372f32392f3564336562653337353332313034363739332e706e67

**Comment by YoshinoriN** [comment]
@code004Accepted 
I confirmed new preview link that its seems no proble.
Would you please add your screenshot to [source/themes/screenshots](https://github.com/hexojs/site/tree/afa56a214e3ff6f79b9eb44f936fcfdc39995641/source/themes/screenshots) directory?

Thanks :)

**Comment by code004Accepted** [comment]
@YoshinoriN The screenshot is added and I checked the preview site. It was working well. Thanks.

**Comment by code004Accepted** [comment]
@YoshinoriN The `Materialized.PNG` file is deleted and the `Materialized.png` is reuploaded. Please check if the preview site works well. Thanks.

**Comment by tomap** [comment]
I fixed the conflict :)

**Comment by code004Accepted** [comment]
> I fixed the conflict :)

Thanks. :)

**Comment by YoshinoriN** [comment]
@tomap Thanks :) 

@code004Accepted 
Thank you for your contribution :)

**Pull request merged**
