### PR TITLE
plugin: hexo-tag-scode & theme: Pure

### PR DESCRIPTION
**Pull request by renbaoshuo**
## Check List

**Please read and check followings before submitting a PR.**

- [x] I want to publish my theme on Hexo official website.
    - [x] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [x] `name` is unique.
    - [x] `link` URL is correct.
    - [x] `preview` URL is correct.
    - [x] `preview` URL web site is rendered correctly.
    - [x] Add a screenshot to `source/themes/screenshots`.
    - [x] Screenshot filename is same as value of `name`.
    - [x] Screenshot size is `800 * 500`.
    - [x] Screenshot file format is `png`.
- [x] I want to publish my plugin on Hexo official website.
    - [x] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [x] `name` is unique.
    - [x] `link` URL is correct.
- [ ] Others (Update, fix, translation, etc...)
    - Languages:
    - [ ] `en` English
    - [ ] `ko` Korean
    - [ ] `pt-br` Brazilian Portuguese
    - [ ] `ru` Russian
    - [ ] `th` Thai
    - [ ] `zh-cn` simplified Chinese
    - [ ] `zh-tw` traditional Chinese

### CODE REVIEW

**Review by jiangtj — APPROVED** [review]
👍

**Comment by stevenjoezhang** [comment]
@renbaoshuo Sorry, but there is already a theme called pure: https://github.com/hexojs/site/pull/533 . Would you mind changing the name of your theme?

**Comment by renbaoshuo** [comment]
> @renbaoshuo Sorry, but there is already a theme called pure: #533 . Would you mind changing the name of your theme?

Sorry, I don't want to change the name of my theme. Because this theme is transplanted from [imhanjie/gridea-theme-pure](https://github.com/imhanjie/gridea-theme-pure).

**Comment by stevenjoezhang** [comment]
https://github.com/renbaoshuo/hexo-tag-scode returns 404

**Pull request merged**
