### PR TITLE
add a new hexo theme snark

### PR DESCRIPTION
**Pull request by Litreily**
Signed-off-by: litreily <707922098@qq.com>

- [x] Read the [theme publishing doc](https://hexo.io/docs/themes#Publishing) or [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).

### CODE REVIEW

**Comment by mkkhedawat** [comment]
Preview link doesn't seem to work.

**Comment by Litreily** [comment]
@mkkhedawat The [preview link](https://www.litreily.top)is work well, can  you check again?

**Comment by mkkhedawat** [comment]
Ohkay, Preview is fine. 
But one issue, Theme name ('Snark') is not same as image name ('snark'), Because of that image is not loading on site. Change one of them.

Steps to reproduce :
```sh
$ cd site
$ npm install 
$ hexo server 
```
visit http://localhost:4000 and go to themes tab, search for your theme listing, Image should load properly.

**Comment by Litreily** [comment]
@mkkhedawat update yet, and test pass, please help to merge, thanks!

**Pull request merged**
