### PR TITLE
[WIP] Add Japanese translation.

### PR DESCRIPTION
**Pull request by desigrammer**
Hello, I translated some of the docs into Japanese.

This is partial translate, so please tell me if you need all of pages are translated,
then I'll change this PR into WIP and translate remaining.

### CODE REVIEW

**Comment by NoahDragon** [comment]
@desigrammer Thanks for your contribution. It's awesome. However, it's better to translate all, otherwise, the rest of the pages will remain blank. Here is an example when translating to Portuguese https://github.com/hexojs/site/pull/605 .

**Comment by desigrammer** [comment]
@NoahDragon I see. I'll change this PR's state to WIP. After I translate remaining pages into Japanese, then I change the state and make order to review this PR.

**Comment by curbengh** [comment]
@desigrammer 
Any update?

**Comment by desigrammer** [comment]
@curbengh 
I'm sorry for your inconvenience. I forgot this PR.
But I cant update this PR now due to my work, so I close this PR.

**Comment by YoshinoriN** [comment]
@desigrammer
Hi. Shall I take over your translation if you are okay?
Aslo, I'm too busy I'm not sure if it can be completed.

**Pull request closed without merging**
