### PR TITLE
theme: hermes (updates)

### PR DESCRIPTION
**Pull request by claymcleod**
Sorry for the multiple pulls so close together — I saw mine on the live site and decided it was too close to the original Apollo theme. Also, I updated the description to reflect that this theme has been updated to work out of the box (Apollo is essentially deprecated).

## Check List

**Please read and check followings before submitting a PR.**

- [x] I want to publish my theme on Hexo official website.
    - [x] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [x] `name` is unique.
    - [x] `link` URL is correct.
    - [x] `preview` URL is correct.
    - [x] `preview` URL web site is rendered correctly.
    - [x] Add a screenshot to `source/themes/screenshots`.
    - [x] Screenshot filename is same as value of `name`.
    - [x] Screenshot size is `800 * 500`.
    - [x] Screenshot file format is `png`.
- [ ] I want to publish my plugin on Hexo official website.
    - [ ] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [ ] `name` is unique.
    - [ ] `link` URL is correct.
- [ ] Others (Update, fix, translation, etc...)

### CODE REVIEW

**Comment by claymcleod** [comment]
Force push because I accidentally included a package bump. Not sure when now this says there are conflicts to resolve, there shouldn't be 🤷‍♂

**Comment by claymcleod** [comment]
@SukkaW does this look okay?

**Comment by SukkaW** [comment]
This PR is still has conflicts that need to be resolved...

**Comment by claymcleod** [comment]
Fixed!

**Comment by NoahDragon** [comment]
Thanks for your contribution. However, this commit is not clean. I have created a new PR #1222 please have a look.

**Pull request closed without merging**
