### PR TITLE
plugins: add hexo-multiauthor

### PR DESCRIPTION
**Pull request by noraj**
## Check List

**Please read and check followings before submitting a PR.**

- [ ] I want to publish my theme on Hexo official website.
    - [ ] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
    - [ ] `name` is unique.
    - [ ] `link` URL is correct.
    - [ ] `preview` URL is correct.
    - [ ] `preview` URL web site is rendered correctly.
    - [ ] Add a screenshot to `source/themes/screenshots`.
    - [ ] Screenshot filename is same as value of `name`.
    - [ ] Screenshot size is `800 * 500`.
    - [ ] Screenshot file format is `png`.
- [x] I want to publish my plugin on Hexo official website.
    - [x] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
    - [x] `name` is unique.
    - [x] `link` URL is correct.
- [ ] Others (Update, fix, translation, etc...)
    - Languages:
    - [ ] `en` English
    - [ ] `ko` Korean
    - [ ] `pt-br` Brazilian Portuguese
    - [ ] `ru` Russian
    - [ ] `th` Thai
    - [ ] `zh-cn` simplified Chinese
    - [ ] `zh-tw` traditional Chinese

### CODE REVIEW

**Comment by jiangtj** [comment]
image

The latest hexo version is 5.4, is it still available?

**Comment by noraj** [comment]
> image
> 
> The latest hexo version is 5.4, is it still available?

Yes, I use it on [my blog](https://blog.raw.pm/) (hexo 5.4) and it's still working.

**Comment by jiangtj** [comment]
image

I found this plugin in npm, but it is strange that it was released by another person after fork

image

**Comment by noraj** [comment]
> image
> 
> I found this plugin in npm, but it is strange that it was released by another person after fork
> 
> image

The original project is here on nmp: https://www.npmjs.com/package/hexo-multiauthor, you made a typo and added a `s` and then ended on a fork (which is as old and unmaintained) https://www.npmjs.com/package/hexo-multiauthors.

**Pull request merged**
