### PR TITLE
add snapshot

### PR DESCRIPTION
**Pull request by ghaseminya**

### CODE REVIEW

**Comment by NoahDragon** [comment]
Please add the theme in the file `source/_data/themes.yml`.

**Comment by ghaseminya** [comment]
@NoahDragon 
edit it in my local repo

**Comment by NoahDragon** [comment]
Great. Merged.

**Comment by ghaseminya** [comment]
Name of snapshot image and name of theme must be equal ?

**Comment by NoahDragon** [comment]
Yes

**Pull request merged**
