### PR TITLE
build: replace gulp with hexo API

### PR DESCRIPTION
**Pull request by curbengh**
## Check List

- [x] Others (Update, fix, translation, etc...)

Part of #1050

### CODE REVIEW

**Comment by SukkaW** [comment]
Should we add this to site script instead of theme script?
All current script are placed under site script directories.

**Comment by SukkaW** [comment]
Also, node version can be specified at `package.json` in this PR, to pass the eslint.

**Comment by tomap** [comment]
I looked at the result on netlify, and it does not seem to work :(

**Comment by curbengh** [comment]
> Should we add this to site script instead of theme script?
> All current scripts are placed under site script directory.

Moved to site script

> Also, node version can be specified at package.json in this PR, to pass the eslint.

Added. Pass travis.

> I looked at the result on netlify, and it does not seem to work :(

could be caused by incompatibility with gulp-cheerio, which is the last holdout 🏰 .

---

The gulp-cheerio replacement might live inside,

https://github.com/hexojs/site/blob/c3ed102a0271f0443b363c545f15e2669ab47b4a/scripts/responsive.js#L62-L64

I'll explore the attributes and values added by gulp-cheerio. Anyone feel free to suggest codes.

**Comment by curbengh** [comment]
Noticed generated themes/index.html has
```
class="plugin-screenshot-img lazyload"
```

while hexo.io shows
```
class="plugin-screenshot-img lazyautosizes lazyloaded"
```

don't think it's modified by gulp nor site script, maybe by `lazyload.js`?

**Comment by curbengh** [comment]
If anyone is curious about the need of insert hash to filename (similar to current gulp process), the hash is for cache busting. Netlify uploads these images to Cloudfront CDN as part of (optional, enabled in Hexo.io) [image optimization](https://www.netlify.com/blog/2019/08/05/control-your-asset-optimization-settings-from-netlify.toml/). Unlike regular Netlify webpage which has aggressive [cache revalidation](https://www.netlify.com/blog/2017/02/23/better-living-through-caching/), Cloudfront set 1-year cache instead, hence the use of cache busting.

**Comment by SukkaW** [comment]
@curbengh 

Netlify add hash in CloudFront URL:

```
https://d33wubrfki0l68.cloudfront.net/css/4c5f2bc7d0402a1c3dcde67d3c809db5afebb942/build/css/navy.css
```

```
https://d33wubrfki0l68.cloudfront.net/css/ba7ee1d8d17f10983373dcc4f1e9992c6883cbe4/build/css/navy.css
```

So it is no need to add hash at our side.

**Comment by curbengh** [comment]
Dropped hash.

**Comment by curbengh** [comment]
The preview LGTM, so I think this is ready.

**Pull request merged**
