### PR TITLE
Added theme Weightless

### PR DESCRIPTION
**Pull request by zllovesuki**

### CODE REVIEW

**Comment by tommy351** [comment]
The size of screenshot should be 800x500

**Comment by zllovesuki** [comment]
My god, I can't read.

**Comment by zllovesuki** [comment]
Alright, I resized the screenshot.

**Comment by stevenjoezhang** [comment]
@zllovesuki Hello, both https://jerry.im/essays/2016/02/hexo-theme-weightless/ and  https://git.fm/zllovesuki/hexo-theme-weightless cannot be accessed. Would you mind updating the link? Thanks!

**Pull request merged**
